Add kratos rock release
canonical/oci-factory pull request #12
Opened 2023-05-11 14:52 UTC by nsklikas

Add files for the [Kratos ROCK](github.com/canonical/kratos-rock/)

Didn't add any documentation or contacts, hope that's ok.

2023-05-11 15:20 UTC, cjdcordeiro commented
Thanks for this contribution. This seems to be a new ROCK and you're asking for it to be released into DH and ECR, so before even starting the review, I suggest you go through the Contributor's Contract (find the link from last week's workshop) and reach out to @valentincanonical about whether this should be under the "ubuntu" namespace or not

2023-05-15 16:35 UTC, valentincanonical requested changes
As discussed, this image might eventually make it to the Ubuntu namespace as part of Canonical's images portfolio but this will happen later when there's better testing, documentation, and the team is ready to commit to supporting these images. 

For now, I suggest removing the release-to / releases options, so that the OCI factory will still build these Rocks but not publish them anywhere beyond the staging GHCR area.

2023-05-15 16:35 UTC, valentincanonical commented on oci/kratos/builds.yaml
> +        - edge
```suggestion
```

2023-08-18 12:21 UTC, cjdcordeiro commented
Hi again! I'm just reviving this thread to know we it should be resumed or closed ;)

(FYI @nsklikas )

2024-12-04 14:39 UTC, closed without merging