(chore) fix new line in bash kafka docs
canonical/oci-factory pull request #173
Opened 2024-05-23 16:23 UTC by deusebio

- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description
Small fix of the docs for Kafka image

2024-05-23 16:47 UTC, cjdcordeiro requested changes

2024-05-23 16:47 UTC, cjdcordeiro commented on oci/kafka/documentation.yaml
> +  docker run --detach --name kafka --network kafka-network -p 9092:9092 kafka:3.6-22.04_edge
```suggestion
  docker run --detach --name kafka --network kafka-network -p 9092:9092 ubuntu/kafka:3.6-22.04_edge
```
right?

2024-05-24 07:14 UTC, deusebio commented on oci/kafka/documentation.yaml
> +  docker run --detach --name kafka --network kafka-network -p 9092:9092 kafka:3.6-22.04_edge
oh yes, great catch!

2024-05-24 07:50 UTC, cjdcordeiro approved these changes
thanks for the fix

2024-05-24 07:50 UTC, merged