docs: Disabling Security Monitoring
canonical/oci-factory pull request #202
Opened 2024-06-21 00:32 UTC by cav72

- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description
A feature has been added to the ROCKS security monitoring that allows for deprecated tags to be specified and skipped from security email notifications.

2024-06-21 08:48 UTC, linostar requested changes
Just a nitpick.

2024-06-21 08:48 UTC, linostar commented on IMAGE_MAINTAINER_AGREEMENT.md
> +- populate the table under the "Deprecated channels & tags" section in the Rock description.
```suggestion
- populate the table under the "Deprecated channels & tags" section in the rock description.
```
Only change "Rock" to "rock" here. "Ubuntu Rock(s)" should stay capitalized.

2024-06-23 23:41 UTC, cav72 commented
> Just a nitpick.

This is now resolved - let me know if you find any other ones like this. Cheers!

2024-06-24 06:45 UTC, linostar commented
> > Just a nitpick.
> 
> This is now resolved - let me know if you find any other ones like this. Cheers!

Thanks. Can you please edit the author on that commit so it can use your launchpad email instead of the current `51986748+cav72@users.noreply.github.com` so that the CLA check on the PR passes?

2024-06-24 07:19 UTC, cav72 commented
> > > Just a nitpick.
> > 
> > 
> > This is now resolved - let me know if you find any other ones like this. Cheers!
> 
> Thanks. Can you please edit the author on that commit so it can use your launchpad email instead of the current `51986748+cav72@users.noreply.github.com` so that the CLA check on the PR passes?

done!

2024-06-25 19:44 UTC, linostar commented
Thanks!

There are some changes going to how the documentation generator generates the section of depreacted tags and channels (see PR https://github.com/canonical/oci-factory/pull/203).

This means that oci-factory will be able to auto-list the deprecated tracks in the aforementioned section, and the rock maintainer won't need to write this section manually anymore. The condition for that to happen is based on the end-of-life value for each track of the image.

I suggest to wait until PR #203 is merged then adjust this PR accordingly to reflect those changes.

2024-06-26 03:51 UTC, cav72 commented
Roger that! Sounds like a plan

2024-09-12 02:18 UTC, cav72 commented
hi @linostar - I was wondering if had any info on the status of #203 to allow this MR to get merged?

2024-09-12 07:22 UTC, linostar commented
> hi @linostar - I was wondering if had any info on the status of #203 to allow this MR to get merged?

Hey. Thanks for a following up. PR 203 was blocked by PR 241, which is hopefully going to be merged in the few upcoming days. Once that done, PR 203 can be merged too and ublock this.

2025-04-08 23:30 UTC, cav72 commented
hi @linostar - was there any more blockers for this one?

2025-04-11 01:02 UTC, cav72 commented
@zhijie-yang - thank you so much for that! Let me know if you need anything else from my end to help

2025-04-11 08:01 UTC, zhijie-yang approved these changes
Looks good to me. Thanks!

2025-04-11 09:40 UTC, merged