Notification and Issue on Vulnerability Scan Failure
canonical/oci-factory pull request #237
Opened 2024-08-29 10:26 UTC by zhijie-yang

- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description

This PR gives the OCI Factory the ability to create issues in the repository of the build rock, if there are failing vulnerability scanning results, keep them updated with the latest scanning results (if changes exist), and notify in the MM channel if new vulnerabilities are found.

### Related issues
ROCKS-1330

2024-08-29 10:35 UTC, zhijie-yang commented
The corresponding `_Test OCI Factory | mock-rock` workflow run should be [this](https://github.com/canonical/oci-factory/actions/runs/10613059951).

2024-08-29 17:06 UTC, cjdcordeiro requested changes

2024-08-29 17:06 UTC, cjdcordeiro commented on .github/workflows/Vulnerability-Scan.yaml
> +      - name: Create issue
```suggestion
      - name: Notify via GitHub issue
```

2024-08-30 08:06 UTC, zhijie-yang commented on .github/workflows/Vulnerability-Scan.yaml
> +          issue_number=$(gh issue list --repo github.com/zhijie-yang/workflow-playground --json "number,title" \
Fixed. Thanks for pointing out.

2024-08-30 09:11 UTC, cjdcordeiro approved these changes
Thanks. LGTM
waiting on @clay-lake

2024-08-30 14:51 UTC, zhijie-yang commented on .github/workflows/Vulnerability-Scan.yaml
> +          echo "| ID | Target |Severity | Package |" >> issue.md
```suggestion
          echo "| ID | Target | Severity | Package |" >> issue.md
```

2024-08-30 14:57 UTC, clay-lake approved these changes
LGTM, Thanks!

2024-08-30 15:05 UTC, merged