[WIP] feat: Add metrics-proxy rock
canonical/oci-factory pull request #267
Opened 2024-10-17 11:08 UTC by IbraAoad

- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description
This PR adds the metrics-proxy ROCK to the OCI factory.

### Related issues

---

*Picture of a cool rock:*
![cool-rock](https://github.com/user-attachments/assets/682233bc-9f29-4948-870e-3672722b162e)

2024-12-03 14:29 UTC, IbraAoad commented
@cjdcordeiro Do you mind taking a look at this as well, thanks! :bowing_man:

2024-12-03 14:44 UTC, cjdcordeiro approved these changes
It lgtm. Thanks. Since it's the 1st PR, I'd also like another colleague to have a 2nd look before merging

FYI @clay-lake @zhijie-yang

2024-12-11 08:41 UTC, zhijie-yang approved these changes
Looks nice to me, thanks! A nitpick for future updates: Please leave a blank line at the end of each file.

2024-12-11 08:46 UTC, clay-lake requested changes
Would it be possible to add a newline at every EOF? I also added a comment about the prior version.

2024-12-11 08:46 UTC, clay-lake commented on oci/metrics-proxy/image.yaml
> +    directory: "0.1.1"
Is it worth adding the [0.1.0](https://github.com/canonical/metrics-proxy-rock/tree/main/0.1.0) rock as well?

2024-12-11 10:38 UTC, clay-lake commented
Quick note: we are waiting for #308 to be merged in. Should be completed shortly.

2024-12-11 16:11 UTC, merged