feat: add 'deprecated' field for depreacted section generation in image docs
canonical/oci-factory pull request #286
Opened 2024-11-13 12:37 UTC by linostar

- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description
The documentation generator for rocks is missing some parts necessary to generate the `Deprecated channels & tags` section.

This PR provides the necessary values so that the generator can identify the deperacted tags and list them accordingly, using the expired end-of-life value of each track to determine whether it is depreacted or not.

### Related issues
OCI-Factory builds won't work if one image's track has an expired EOL value. Another PR to fix that issue will be out soon.

2024-11-13 17:35 UTC, zhijie-yang requested changes

2024-11-13 17:35 UTC, zhijie-yang commented on src/docs/generate_oci_doc_yaml.py
Some of your changes in `src/docs/generate_oci_doc_yaml.py` are not cherry-picked here.

2024-11-15 12:10 UTC, linostar commented
@clay-lake  @zhijie-yang This is ready for review.

The result can be seen on [Dockerhub's mock-rock page](https://hub.docker.com/r/rocksdev/mock-rock), where track `1.0-22.04` appears in the deprecated section because its EOL is `2024-05-01`.

2024-11-19 10:46 UTC, zhijie-yang commented
![image](https://github.com/user-attachments/assets/f967a387-f418-4381-b730-8a9b872b9b0d)
![image](https://github.com/user-attachments/assets/933335ef-47e8-4a94-93c3-98b25a7b5cc9)
Screenshots for the documentation on DockerHub.

2024-11-19 10:50 UTC, zhijie-yang approved these changes
Looks good to me. Thanks! @clay-lake wdyt?

2024-11-20 13:16 UTC, clay-lake approved these changes
Minor nit, but LGTM otherwise! Thanks.

2024-11-20 13:49 UTC, linostar commented on src/image/release.py
> +        if upload_release_dict and upload_release_dict.get("end-of-life"):
Applied your suggestion.

2024-11-20 14:01 UTC, merged