Issue for distinct revisions when vulnerabilities are found
canonical/oci-factory pull request #295
Opened 2024-11-22 14:09 UTC by zhijie-yang

- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description
1. GitHub issues will be created w.r.t. each revision of an image that contains CVEs found in the vulnerability scanning workflows triggered with continuous testing workflow. In the report, all the affected tags associated with the revision will be included in the report.
2. When vulnerabilities are found for the images tested in the `Image` workflow triggered by a push, a pull request or a workflow dispatch event, the vulnerability report will be dumped to a summary instead of creating an issue at the image repo.
3. This shall fix the issue that an issue will be accidentally closed when the different risks in a track of an image are tagged to different revision, and only some of the revisions have found CVEs.

2024-11-25 09:29 UTC, clay-lake requested changes

2024-11-25 09:29 UTC, clay-lake commented on src/shared/release_info.py
> +    parser.add_argument(
I think we should create an individual store_true flag to execute get_revision_to_released_tags. We could even make it mutually exclusive of other "command" flags if required. That way it is integrated into the --help info.

2024-11-25 09:29 UTC, clay-lake commented on tests/unit/test_shared_release_info.py
> +        "Tag 1.19.0-22.04_candidate was caught in a circular dependency, following tags that follow themselves. Cannot pin a revision."
nit:   I think we over constraining the tests to check for this string. Maybe it is good enough that we assert BadChannel is raised. We could also then create a new exception class for circular dependencies if we need to single out this exact scenario.

2024-11-25 10:05 UTC, zhijie-yang commented on .github/workflows/Vulnerability-Scan.yaml
> +      - run: pip install pydantic==2.8.2
We can, but they contain many things beyond the requirements for this job.

2024-11-25 15:49 UTC, SamirPS commented on .github/workflows/Vulnerability-Scan.yaml
> +        description: 'If to create a GitHub issues for found vulnerabilities'
you can remove the If :)

2024-11-26 09:39 UTC, clay-lake approved these changes
There a few things we should work on later, but they might be out of scope of this PR. 

This is a nice feature! :+1:

2024-11-26 09:41 UTC, merged