add valkey to oci-factory
canonical/oci-factory pull request #306
Opened 2024-12-06 12:40 UTC by reneradoi

- [X] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [X] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description
This PR adds the valkey rock to the OCI factory. The onboarding issue can be found [here](https://github.com/canonical/oci-factory/issues/305).

---

*Picture of a cool rock:*

2025-01-09 16:30 UTC, cjdcordeiro commented
@zhijie-yang I think we can no longer use our self-hosted runners, according to https://github.com/canonical/oci-factory/actions/runs/12694115078/job/35383511241?pr=306.

We'll need to discuss this offline as it will affect arm64 builds. 

(FYI @reneradoi )

2025-01-14 07:24 UTC, reneradoi commented
Hello @cjdcordeiro I just wanted to update on this topic. Is anything still to be done from my side? I see that one CI step is failing, but I'm not sure if this is related to my PR or to your previous comment.

What are the next steps for publishing the image to Dockerhub?

2025-01-14 10:37 UTC, cjdcordeiro commented
Hi @reneradoi there isn't yet a fix but I'm trying to apply a patch and change a few settings, even if temporarily, just to get this going

2025-01-14 10:58 UTC, cjdcordeiro requested changes
It seems there's a CVE to be addressed:

> '[{"Target":"usr/bin/redis_exporter","LastModifiedDate":"2024-09-09T15:35:07.573Z","VulnerabilityID":"CVE-2024-34156","PkgName":"stdlib","Severity":"HIGH"}]'

If you cannot fix it, then see https://github.com/canonical/oci-factory?tab=readme-ov-file#Vulnerability-Filtering

2025-01-14 14:00 UTC, reneradoi commented
The vulnerability has been patched now.

2025-01-14 15:05 UTC, cjdcordeiro requested changes
Sry for the extra pass, but it would also be good to expand a bit more on the documentation. Here's an example: https://github.com/canonical/oci-factory/blob/main/oci/grafana/documentation.yaml

2025-01-14 18:31 UTC, reneradoi commented
I've updated the `documentation.yaml` and added usage information.

2025-01-15 07:26 UTC, cjdcordeiro approved these changes
tyvm for the changes. lgtm ;)

2025-01-15 07:26 UTC, merged