feat: add alertmanager rock
canonical/oci-factory pull request #41
Opened 2023-08-16 13:27 UTC by lucabello

- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description
This PR adds the Alertmanager ROCK to the oci-factory.

Please note that this should go to a new `alertmanager` repository that's yet to be created. There currently exists a [prometheus-alertmanager](https://hub.docker.com/r/ubuntu/prometheus-alertmanager) repository, but that one should be deprecated.

### Related issues
(none)

2023-08-18 09:51 UTC, cjdcordeiro requested changes
Keep them coming :D

Just a small typo to fix, but it LGTM ;)

2023-08-18 09:51 UTC, cjdcordeiro commented on oci/alertmanager/documentation.yaml
> +  Read more on the [official documentation](https://prometheus.io/docs/alerting/latest/alertmanager/)
```suggestion
  The Alertmanager handles alerts sent by client applications such as the
  Prometheus server. It takes care of deduplicating, grouping, and routing them
  to the correct receiver integrations such as email, PagerDuty, OpSGenie, or
  many other mechanisms thanks to the webhook receiver. It also takes care of
  silencing and inhibition of alerts.
  Read more on the [official documentation](https://prometheus.io/docs/alerting/latest/alertmanager/)
```

2023-08-22 07:21 UTC, lucabello commented
Fixed, thanks!

2023-08-22 15:01 UTC, merged

2023-08-22 15:28 UTC, cjdcordeiro commented
@lucabello this image also failed the efficiency and vulnerability tests-> https://github.com/canonical/oci-factory/actions/runs/5940848690/job/16110358625